# config.yml

concurrency:
  max_workers: 5

http:
  timeout: 10
  backoff_factor: 2
  max_retries: 3

user_agents:
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64)..."
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)..."
  - "Mozilla/5.0 (X11; Linux x86_64)..."

proxies: []
